SportDay/SportDay/Controllers/BookingsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using SportDay.Models;
using SportDay.Units;

namespace SportDay.Controllers
{
    public class BookingsController : Controller
    {
        private SportDayModel db = new SportDayModel();

        // GET: Bookings
        [Authorize]

        public ActionResult Index()
        {
            var userId = User.Identity.GetUserId();
            var bookings = db.Bookings.Where(b => b.AspNetUser.Id == userId).Include(b => b.Event);
            return View(bookings.ToList());
        }

        public ActionResult Calendar()
        {
            return View();

        }

        // GET: Bookings/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Booking booking = db.Bookings.Find(id);
            if (booking == null)
            {
                return HttpNotFound();
            }
            return View(booking);
        }

        // GET: Bookings/Create
        public ActionResult Create(string date)
        {

            string idd = User.Identity.GetUserId();
            var USER = db.AspNetUsers.Where(s => s.Id == idd).ToList();
            //var events = db.Events.Where(e => e.EventId == id).ToList();

            //Event ev = db.Events.Find(id);
            // DateTime start = ev.StartDate;
            // DateTime end = ev.EndDate;
            // List<DateTime> lista = new List<DateTime>();

            // foreach (DateTime day in EachDay(start, end)) { lista.Add(day)};

            ViewBag.UserId = new SelectList(USER, "Id", "Email");
            ViewBag.EventId = new SelectList(db.Events, "EventId", "Name");

            if (null == date)
                return RedirectToAction("Index");

            Booking e = new Booking();
            DateTime convertedDate = DateTime.Parse(date);
            e.Date = convertedDate;
            ViewBag.Date = date;
            return View();
        }


        // POST: Bookings/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "BookingId,Info,UserId,EventId,Date")] Booking booking)
        {

            booking.UserId = User.Identity.GetUserId();
            var id = booking.EventId;
            Event ev = db.Events.Find(id);
            DateTime start = ev.StartDate;
            DateTime end = ev.EndDate;
            ModelState.Clear();
            TryValidateModel(booking);

            if (DateTime.Compare(DateTime.Now, end) > 0)
            {
                ModelState.AddModelError("", "Sorry, The Event was end.");
            }
            else if (DateTime.Compare(start, booking.Date) > 0 || DateTime.Compare(booking.Date, end) > 0)
            {
                ModelState.AddModelError("", "The date is not avilable.");

            }
            else if (ModelState.IsValid) {
                db.Bookings.Add(booking);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            string idd = User.Identity.GetUserId();
            var USER = db.AspNetUsers.Where(s => s.Id == idd).ToList();
            ViewBag.UserId = new SelectList(USER, "Id", "Email");
            ViewBag.EventId = new SelectList(db.Events, "EventId", "Name", booking.EventId);
            
                String email = USER[0].Email;
                String subject = "Hi" + " "+ email;
                String contents = "You have successful booking the event:" + ev.Name;

                EmailSender es = new EmailSender();
                es.Send(email, subject, contents);


                return View(booking);
            
        }

        // GET: Bookings/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Booking booking = db.Bookings.Find(id);
            if (booking == null)
            {
                return HttpNotFound();
            }
            string idd = User.Identity.GetUserId();
            var USER = db.AspNetUsers.Where(s => s.Id == idd).ToList();
            ViewBag.UserId = new SelectList(USER, "Id", "Email", booking.UserId);

            return View(booking);
        }

        // POST: Bookings/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "BookingId,Info,UserId,EventId,Date")] Booking booking)
        {
            if (ModelState.IsValid)
            {
                db.Entry(booking).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.UserId = new SelectList(db.AspNetUsers, "Id", "Email", booking.UserId);
            ViewBag.EventId = new SelectList(db.Events, "EventId", "Name", booking.EventId);
            return View(booking);
        }

        // GET: Bookings/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Booking booking = db.Bookings.Find(id);
            if (booking == null)
            {
                return HttpNotFound();
            }
            return View(booking);
        }

        // POST: Bookings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Booking booking = db.Bookings.Find(id);
            db.Bookings.Remove(booking);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SportDay/SportDay/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link rel="stylesheet" href="~/Content/Footer.css">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body style=" flex: 1;">
    <div style="margin-bottom: 0.8cm">
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                </div>

                <div class="navbar-collapse collapse">
                    <div align="center" style="height: 30px; font-family: Brush Script MT, Brush Script Std, cursive; color: cornflowerblue; text-shadow: 0.2em 0.5em 0.1em #600, -0.3em 0.1em 0.1em #060, 0.4em -0.3em 0.1em #006; font-size: 50px "><p>Sport Day</p></div>
                    <div style="position:relative;right:200px">
                        <ul class="nav navbar-nav">
                            <li style="font-size: 30px; font-family: Impact, fantasy ">@Html.ActionLink("Home", "Index", "Home")</li>
                            <li style="font-size: 30px; font-family: Impact, fantasy ">@Html.ActionLink("Events", "Index", "Events")</li>
                            <li style="font-size: 30px; font-family: Impact, fantasy ">@Html.ActionLink("Send FeedBack", "Contact", "Home")</li>
                            @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                            {

                                <li style="font-size: 30px; font-family: Impact, fantasy ">@Html.ActionLink("EventTypes", "Index", "EventTypes")</li>

                            }
                            @if (User.Identity.IsAuthenticated && User.IsInRole("User"))
                            {
                                <li style="font-size: 30px; font-family: Impact, fantasy ">@Html.ActionLink("Booking", "Index", "Bookings")</li>

                            }
                        </ul>
                    </div>
                    <div style="position:relative;left:700px">
                        <ul class="nav navbar-nav">
                            <li style="font-size: 30px; font-family: Impact, fantasy ">@Html.Partial("_LoginPartial")</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>

    @RenderBody()
    <hr />
    <div class="footer-dark" style="position: relative; bottom: -500px; min-height: 40vh; ">
        <footer>
            <div class="container">
                <div class="row">
                    <div class="col-sm-6 col-md-3 item">
                        <h3>Services</h3>
                        <ul>
                            <li>@Html.ActionLink("Home", "Index", "Home")</li>
                            <li>@Html.ActionLink("Send FeedBack", "Contact", "Home")</li>
                        </ul>
                    </div>
                    <div class="col-sm-6 col-md-3 item">
                        <h3>About</h3>
                        <ul>
                            <li><a href="#">Company</a></li>
                            <li><a href="#">Team</a></li>
                            <li><a href="#">Careers</a></li>
                        </ul>
                    </div>
                    <div class="col-md-6 item text">
                        <h3>SportDay</h3>
                        <p>Location:Melbourne</p>
                        <p>Telphone:1234567</p>
                    </div>

                </div>

            </div>
        </footer>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"></script>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

</body>
</html>